### Data Encoding

#### this is just for to change the value from categories to numerical value to train the model because the machine need the value likke to understand the value in numerices

##### there are three types of data encoding

##### 1.nominal encoding/one hot encoding(OHE)   2.label and ordinal encoding     3.target guided ordinal encoding

In [72]:
### one hot encoding(OHE)
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [73]:
## creat a sample data frame
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'red', 'blue', ]
})

In [74]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [75]:
### create an OneHotEncoder instance
encoder=OneHotEncoder()

In [76]:
### perform fit and then transform
encoded=encoder.fit_transform(df[['color']]).toarray()   ## sparse Matrix is used to eleminate the zero from the the data to make the memory lightweight

In [77]:
import pandas as pd
encoder_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out(['color']))

In [78]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [79]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [80]:
## for any ner data
encoder.transform([['blue']]).toarray()

d:\data analysis\python\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [81]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [82]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [83]:
## i have to solve this problem using OHE

#### Label Encoding

label encoding and ordinal encoding are two techinique used to encode categorical data as numerical data(This we use order vlaue not like nomination type(no order))

In [84]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [85]:
lbl_encoder.fit_transform(df['color'])

array([2, 0, 1, 1, 2, 0])

In [86]:
## if we give any values
lbl_encoder.transform(['blue'])

array([0])

In [87]:
lbl_encoder.transform(['red'])

array([2])

In [88]:
lbl_encoder.transform(['green'])

array([1])

### ordinal encoding

In [89]:
### it is used for to put data in order
### ordinal encoding
from sklearn.preprocessing import OrdinalEncoder

In [90]:
## creat a sample data frame
df = pd.DataFrame({
    'size': ['small', 'medium', 'large', 'medium', 'small', 'large']
})

In [91]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [92]:
## creat an instance of OrdinalEncoder adn then fit_transformation
encoder= OrdinalEncoder(categories=[['small', 'medium', 'large']])

In [93]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [94]:
encoder.transform([['medium']])

d:\data analysis\python\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[1.]])

### Target guided ordianal encoding

In [99]:
import pandas as pd
## creat a sample dataframe with a categorical variable and a target variable
df_price= pd.DataFrame({
  'city' : ['delhi', 'dublin', 'london', 'delhi', 'london', 'dublin', 'delhi'],
  'price' : [200, 150, 300, 250, 350, 120, 220]
})

In [100]:
df_price

     city  price
0   delhi    200
1  dublin    150
2  london    300
3   delhi    250
4  london    350
5  dublin    120
6   delhi    220

In [107]:
mean_price = df.groupby('city')['price'].mean().to_dict()

In [108]:
mean_price

{'delhi': 223.33333333333334, 'dublin': 135.0, 'london': 325.0}

In [109]:
df['city_encoded'] = df['city'].map(mean_price)

In [111]:
df[['price', 'city_encoded']]

   price  city_encoded
0    200    223.333333
1    150    135.000000
2    300    325.000000
3    250    223.333333
4    350    325.000000
5    120    135.000000
6    220    223.333333

In [113]:
import seaborn as sns
sns.load_dataset('titanic')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True