### Handling imbalanced dataset

###### 1.Up Sampling
###### 2.Down Sampling

In [7]:
import numpy as np
import pandas as pd
## set the random seed for reproducibility
np.random.seed(123)

## create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [8]:
n_class_0, n_class_1

(900, 100)

In [9]:
## create my dataframe with imbalanced dataset
class_0 = pd.DataFrame({
    'feature1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target':[0]*n_class_0
})  

class_1 = pd.DataFrame({
    'feature1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target':[1]*n_class_1
})

In [10]:
df = pd.concat([class_0, class_1]).reset_index(drop=True)  ##Reseta_index work as fix the

In [11]:
df.head()

   feature1  feature2  target
0 -1.085631  0.551302       0
1  0.997345  0.419589       0
2  0.282978  1.815652       0
3 -1.506295 -0.252750       0
4 -0.578600 -0.292004       0

In [12]:
df.tail()

     feature1  feature2  target
995  1.376371  2.845701       1
996  2.239810  0.880077       1
997  1.131760  1.640703       1
998  2.902006  0.390305       1
999  2.697490  2.013570       1

In [13]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [14]:
## upsampling
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [15]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in d:\data analysis\python\venv\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in d:\data analysis\python\venv\lib\site-packages (from scikit-learn) (2.0.1)
Requirement already satisfied: scipy>=1.8.0 in d:\data analysis\python\venv\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in d:\data analysis\python\venv\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in d:\data analysis\python\venv\lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [16]:
from sklearn.utils import resample
df_minority_upsampled = resample(df_minority,replace=True, ##Sample with replacement
         n_samples=len(df_majority), ##to match majority class
         random_state=42
        ) ##reproducible results

In [18]:
df_minority_upsampled.shape

(900, 3)

In [19]:
df_minority_upsampled.head()

     feature1  feature2  target
951  1.125854  1.843917       1
992  2.196570  1.397425       1
914  1.932170  2.998053       1
971  2.272825  3.034197       1
960  2.870056  1.550485       1

In [21]:
pd.concat([df_majority, df_minority_upsampled])

     feature1  feature2  target
0   -1.085631  0.551302       0
1    0.997345  0.419589       0
2    0.282978  1.815652       0
3   -1.506295 -0.252750       0
4   -0.578600 -0.292004       0
..        ...       ...     ...
952  1.188902  2.189189       1
965  3.919526  1.980541       1
976  2.810326  3.604614       1
942  3.621531  2.168229       1
974  1.160887  2.489203       1

[1800 rows x 3 columns]

In [22]:
## downsapmling
## set the random seed for reproducibility
np.random.seed(123)

## create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

## create my dataframe with imbalanced dataset
class_0 = pd.DataFrame({
    'feature1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target':[0]*n_class_0
})  

class_1 = pd.DataFrame({
    'feature1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target':[1]*n_class_1
})

df = pd.concat([class_0, class_1]).reset_index(drop=True)  ##Reset_index work as fix the numbering after concat

## check the class distrubation
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [23]:
## downsampling
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [24]:
from sklearn.utils import resample
df_majority_downsampled = resample(df_majority,replace=False,
         n_samples=len(df_minority), ##to match majority class
         random_state=42
        ) ##reproducible results

In [26]:
df_majority_downsampled.shape

(100, 3)

In [27]:
df_downsampled=pd.concat([df_majority_downsampled, df_minority])

In [28]:
df_downsampled.target.value_counts()

target
0    100
1    100
Name: count, dtype: int64